/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vect.h"

bool_t
xdr_vectors (XDR *xdrs, vectors *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vector.vector_val, (u_int *) &objp->vector.vector_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vector_pair (XDR *xdrs, vector_pair *objp)
{
	register int32_t *buf;

	 if (!xdr_vectors (xdrs, &objp->vector_a))
		 return FALSE;
	 if (!xdr_vectors (xdrs, &objp->vector_b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_make_vector (XDR *xdrs, make_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_vector_pair (xdrs, &objp->pair))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->r))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_results_3 (XDR *xdrs, results_3 *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->avg.avg_val, (u_int *) &objp->avg.avg_len, 2,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_results_4 (XDR *xdrs, results_4 *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->new_vector.new_vector_val, (u_int *) &objp->new_vector.new_vector_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
