/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vect.h"
#include <stdio.h>
#include <math.h>

float *		//Λογική του μέτρου διανύσματος
mag_1_svc(vectors *argp, struct svc_req *rqstp)
{
	static float  result = 0;
	int temp = 0;


	for (int i = 0; i < argp->n;i++){
		temp += pow(argp->vector.vector_val[i], 2);
	}

	result = (float) pow(temp, 0.5);

	return &result;
}

int *		//Λογική εσωτερικού γινομένου διανυσμάτων
dotprod_1_svc(vector_pair *argp, struct svc_req *rqstp)
{
	static int  result = 0;
	int temp = 0;

	for (int i = 0; i < argp->vector_a.n; i++)
	{
		temp += argp->vector_a.vector.vector_val[i] * argp->vector_b.vector.vector_val[i];
	}

	result = temp;

	return &result;
}

results_3 *		//Λογική της μέσης τιμής των διανυσμάτων
vecavg_1_svc(vector_pair *argp, struct svc_req *rqstp)
{
	static results_3  result;
	int sum_a = 0;
	int sum_b = 0;

	for (int i = 0; i < argp->vector_a.n; i++)
	{
		sum_a += argp->vector_a.vector.vector_val[i];
		sum_b += argp->vector_b.vector.vector_val[i];
	}

	result.avg.avg_len = 2;
	result.avg.avg_val = malloc(sizeof(float) * 2);
	result.avg.avg_val[0] = (float) sum_a / argp->vector_a.n;
	result.avg.avg_val[1] = (float) sum_b / argp->vector_a.n;

	return &result;
}

results_4 *		//Λογική της δημιουργίας καινούργιου διανύσματος
newvec_1_svc(make_vector *argp, struct svc_req *rqstp)
{
	static results_4  result;

	result.new_vector.new_vector_len = argp->pair.vector_a.n;
	result.new_vector.new_vector_val = malloc(argp->pair.vector_a.n*sizeof(float));

	for (int i = 0; i < argp->pair.vector_a.n; i++)
	{
		result.new_vector.new_vector_val[i] = argp->r*(argp->pair.vector_a.vector.vector_val[i] + argp->pair.vector_b.vector.vector_val[i]);
	}

	return &result;
}
